/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {



    }
}
