/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

public class App {


    public static void main(String[] args) {

//        Path bmp = FileSystems.getDefault().getPath("assets", "LAND.BMP");

        File input = new File(args[0]);

        //transformBMP(bmp);
    }

    public static void transformBMP(Path bmp){
        File bmpFile = new File(bmp);
        BufferedImage image = ImageIO.read(bmpFile);


    }
}
